### ISSUE TITLE
[BUG] Global hotkeys non-functional on Cinnamon when installed via DEB package

### ISSUE THREAD

**Issue by HarukaYamamoto0** [gustavosett/Windows-11-Clipboard-History-For-Linux#16]
## 🐛 Bug Description

Installing via `.deb` package on Linux Mint 22.2 (Cinnamon 6.4.8) results in three issues:

1. **Global hotkeys (`Super+V` / `Ctrl+Alt+V`) don't work** unless the app is manually launched from the application menu
2. **System tray icon displays as a generic blue circle** instead of the app icon
3. **Window transparency is too high**, making it difficult to read content as it blends with the desktop background

## 📋 Steps to Reproduce

1. Download `win11-clipboard-history_*.deb` from [Releases](https://github.com/gustavosett/Windows-11-Clipboard-History-For-Linux/releases)
2. Install: `sudo apt install ./win11-clipboard-history_*.deb`
3. Try pressing `Super+V` or `Ctrl+Alt+V` → **nothing happens**
4. Launch app from application menu (works fine)
5. Check system tray → **blue circle icon instead of clipboard icon**
6. Open app window → **text is hard to read due to excessive transparency**

## ✅ Expected Behavior

- Global hotkeys should work immediately after installation
- System tray should display the proper application icon
- Window transparency should be balanced for readability

## ❌ Actual Behavior

- **Hotkeys only work after manual setup** of input group permissions (Even though in the release notes of the last release you said that .deb and .rpm already fix this.)
- **Tray icon shows generic fallback** (blue circle)
- **Window transparency makes UI hard to use** against busy desktop backgrounds

## 📸 Screenshots

<img width="819" height="870" alt="Image" src="https://github.com/user-attachments/assets/66befe86-b27a-46e1-9161-2eaf2fc6f3ca" />

## 🖥️ Environment

- **OS**: Linux Mint 22.2 Zara (based on Ubuntu 24.04)
- **Desktop Environment**: Cinnamon 6.4.8
- **Display Server**: X11
- **App Version**: Latest from GitHub releases
- **Installation Method**: DEB package
- **CPU**: Intel Xeon E5-2697 v3
- **GPU**: AMD Radeon RX 570 (amdgpu driver)

## 📝 Root Cause Analysis

After investigation, I discovered:

1. **Hotkey issue**: The `.deb` package doesn't automatically configure `/dev/input` permissions or add user to `input` group. The one-line installer script handles this, but users installing the `.deb` manually are left with non-functional hotkeys.

   Running `groups` shows I'm not in the `input` group:
```
   harukadev adm cdrom sudo dip plugdev users lpadmin sambashare libvirt
```

   The app is running (`pgrep -fa win11-clipboard` returns PID 14368) but can't capture global hotkeys without proper permissions.

2. **Icon issue**: Likely a theme compatibility problem with Cinnamon's system tray not finding the SVG icon in the expected path.

3. **Transparency issue**: Appears to be hardcoded in the UI with no configuration option available yet.

### 1. For Hotkeys (High Priority)
Either:
- **Option A**: Make the `.deb` postinstall script handle permissions automatically (add user to `input` group, create udev rules)
- **Option B**: Add a clear warning in the README that `.deb` users MUST run the manual permission setup from the "Manual Installation" section
- **Option C**: Show a notification on first launch if permissions are missing, with instructions

### 2. For System Tray Icon (Medium Priority)
- Investigate icon path resolution on Cinnamon
- Consider bundling a PNG fallback alongside SVG
- Test with different Cinnamon themes

### 3. For Transparency (Medium Priority)
- Add a settings panel with transparency slider (0-100%)
- Default to ~85% opacity for better readability
- Save preference to config file

**Then log out and log back in.**

## 📄 Additional Context

This is specifically a Cinnamon desktop environment report, but the permission issue likely affects all desktop environments when using the `.deb` package. The one-line installer script works around this using ACLs, but many users (myself included) prefer not to run `curl | bash` scripts for security reasons.

Would be great to have the `.deb` package be fully functional out-of-the-box, or at minimum, clearer documentation about the required manual steps.

**Comment by dashio-ctrl** [comment]
I'll try to fix that

**Comment by gustavosett** [comment]
LGTM

**Comment by gustavosett** [comment]
@dashio-ctrl reverted, worked on dev for me but broke on easy install
your approach was correct, but we need to know what's happening, I'm going to take a look later

**Comment by dashio-ctrl** [comment]
same 🤔

**Comment by gustavosett** [comment]
still not working, reverted again, sorry @dashio-ctrl
I ensured it worked by installing locally and replicating the release installation, but even after working locally, the one-line install problem persisted.

**Comment by gustavosett** [comment]
Could you test @HarukaYamamoto0 ?

**Comment by HarukaYamamoto0** [comment]
Hi, I tested the latest commit and wanted to report the current status.

**What works now**

* The tray icon is now showing correctly.

**What still doesn’t work**

* Start on boot.
* Global shortcuts are still not detected automatically.
* Even after reinstall + reboot, shortcuts only work after manual system changes.

After debugging locally, I found that shortcuts only start working after granting access to `/dev/input/event*`.
The current `postinstall` configures `uinput`, but does not add permissions for input event devices.

**Suggested fix (postinstall)**

Add this rule alongside the existing `uinput` rule:

```udev
KERNEL=="event*", SUBSYSTEM=="input", MODE="0660", GROUP="input", TAG+="uaccess"
```

And trigger input devices as well:

```bash
udevadm trigger --subsystem-match=input --action=change
```

With this change, shortcuts start working without any manual steps.

**UI feedback**

* The tray icon looks good now.
* Background transparency still feels too high.
* It would be great to have either:

  * a runtime transparency setting, or
  * an option to disable transparency and use a solid background.

Not sure if Tauri allows dynamic transparency changes, but even a simple toggle would improve usability a lot.

**Comment by gustavosett** [comment]
Hey @HarukaYamamoto0 I just deployed a new version 7 minutes ago, could you test it? I just refactored the entire shorcut system. About the transparency, I'll take care of that this week.

I appreciate the suggestions, the adjustments will be implemented! 🤠

**Comment by HarukaYamamoto0** [comment]
Perfect, after the new `0.3.3` update, global shortcuts are now working correctly. Thanks for that.

One thing still missing: the app needs to be **manually started** after installation and also after every boot. A startup mechanism would help here.
Ideally, when the shortcut is pressed, it could:

* check if an instance is already running, and
* if not, start the app and open it automatically.

Regarding the UI: background transparency has improved noticeably, but personally I would still prefer an option to use a **solid background color** instead of transparency.

Overall, this update fixed the major blocker. Happy to test further if needed.
