### ISSUE TITLE
[BUG] The letter "v" appears in text fields.

### ISSUE THREAD

**Issue by FabioOJacob** [gustavosett/Windows-11-Clipboard-History-For-Linux#40]
## 🐛 Bug Description

When I press Super+v, the letter "v" is typed if the cursor is in a text field. This could be the terminal, a text editor, a chat, etc. This doesn't happen when I use Ctrl+Alt+v.

## 📸 Screenshots

<img width="1097" height="787" alt="Image" src="https://github.com/user-attachments/assets/42ee4bec-8418-44f2-9b88-32a2d4979f8d" />

## 🖥️ Environment

OS: Debian GNU/Linux 13 (trixie) x86_64
Host: 81FD (Lenovo ideapad 330-15IKB)
Kernel: Linux 6.12.41+deb13-amd64
Uptime: 4 hours, 46 mins
Packages: 3721 (dpkg), 9 (flatpak), 8 (snap)
Shell: bash 5.2.37
Display (LG HDR WFHD): 2560x1080 @ 75 Hz in 34" [External]
DE: Cinnamon 6.4.10
WM: Muffin (X11)
WM Theme: Yaru-cinnamon-dark (Default)
Theme: Adwaita-dark [GTK2/3/4]
Icons: Yaru-Mint-purple [GTK2/3/4]
Font: Sans (9pt) [GTK2/3/4]
Cursor: breeze (24px)
Terminal: GNOME Terminal 3.56.2
Terminal Font: Noto Mono (11pt)
CPU: Intel(R) Core(TM) i3-7020U (4) @ 2.30 GHz
GPU: Intel HD Graphics 620 @ 1.00 GHz [Integrated]

\* Congratulations on the program, it was the missing piece in the Linux world.

**Comment by gustavosett** [comment]
Hi @FabioOJacob, how are you? Thank you for sharing your experience, I will fix this problem! I noticed that problem before, but it's quite rare and difficult to reproduce in my environment. I'll try to find a way to make my environment similar to yours.

**Comment by gustavosett** [comment]
Hi @FabioOJacob, thank's for reporting this issue.

I believe this issue was solved in the latest release. Please try running the installer again:
```bash
curl -sL http://install-clipboard.gustavosett.dev | bash
```

Let me know if this solves it for you! 🤠

**Comment by Tallin-BTC** [comment]
hi @gustavosett , i am using an ubuntu 24.04 and this bug still exists in ver. 0.3.11

It is not fixed.

**Comment by FabioOJacob** [comment]
Excellent @gustavosett, the new version 0.3.11 solved the problem to me. 

<img width="1035" height="371" alt="Image" src="https://github.com/user-attachments/assets/d688bacb-d5f9-4506-8912-4ed36a6828a9" />

The "v" no longer appears when I press Super+V, and the Clipboard window is now displayed.

Thank you for the quick fix.

**Comment by Tallin-BTC** [comment]
It still exists for me im not lying, but its as you said initially that its hard to recreate, sometimes it works other times it just says ^V

<img width="1158" height="659" alt="Image" src="https://github.com/user-attachments/assets/7c5b7b99-5497-40e3-80f8-316fc32820c8" />

or is it now working coz i already have it installed? then how do i update it?

**Comment by gustavosett** [comment]
Hi @Tallin-Boston-Technology, I believe in you haha it happens here but it's really rare on my environment, I really need to understand what's happening... I'm still investigating here.

**Comment by gustavosett** [comment]
@Tallin-Boston-Technology I recommend that you also try the latest version. I've made some changes to the permissions(not focused on this issue but...) that might solve your issue. 

```bash
curl -fsSL https://raw.githubusercontent.com/gustavosett/Windows-11-Clipboard-History-For-Linux/master/scripts/install.sh | bash
```

**Comment by Tallin-BTC** [comment]
Im sorry but it still exists, also the other bug that ive reported in another thread still exists as well.....its just evolved into something else now 😅 (this emoji worked from your clipboard so sometimes it works), ive attached a vid so see through and thank you for your efforts and listening to me anyways

https://github.com/user-attachments/assets/eea522f6-a117-4ddc-a056-5ecfa75dc476

you cant see the mouse in the vid but i was desperately clicking in the clipboard to paste it

**Comment by gustavosett** [comment]
@Tallin-Boston-Technology It seems you have two different versions open at the same time. Since I had to update some things for compatibility with Arch, etc., your system must have opened both versions simultaneously because they have a slight difference in package configurations, and tauri-plugin-single-instance plugin probably couldn't identify them.

I recommend closing those instances as they shouldn't coexist again. By the way, I'll focus entirely on your problem because this shouldn't happen. **I apologize for this situation and thank you very much for reporting the problem.**

**Comment by Tallin-BTC** [comment]
thank you @gustavosett but unfortunately the problem persists, i closed all appl. and restarted my laptop and the problem remained. few things that i would like to mention before i forget is that the ^V problem only shows up if i use the alt shortcut (ctrl + alt + v) and its doesnt paste anything at all if i use the main shortcut (super + v). also 

curl -fsSL https://raw.githubusercontent.com/gustavosett/Windows-11-Clipboard-History-For-Linux/master/scripts/install.sh | bash

this link for some reason doesnt update at all, it just says you already have the latest version installed even though a newer version was available.
Sorry for troubling you so much so that you are prioritizing my problems more, i found your project in a reddit thread when you were helping someone else who also wanted a clipboard for linux and you helped us out. I will be away for a bit so i wont be able to reply to you until atleast tmrw. Thank you and i'll update to the latest ver. (if available) tmrw when i get back

**Comment by gustavosett** [comment]
<img width="325" height="194" alt="Image" src="https://github.com/user-attachments/assets/bf9d5657-94cb-4e25-84f0-f3691f3e1e26" />
Now I can reproduce, I'll focus on this issue now!

**Comment by FabioOJacob** [comment]
Hi @gustavosett, I installed the latest version, 0.4.15, and encountered the following problems:

1) Pinned clipboards are cleared at each login.
2) When copying text with styles, the styles are lost when pasted, it's as if you were pasting plain text.

It would be great if you could resolve these issues. And a suggestion: if the main window had a button to access the settings, something like a gear icon, I think that would be very helpful.

**Comment by gustavosett** [comment]
Hi @FabioOJacob 

1. Is the same behavior as the Windows clipboard, but I'm thinking about it
2. Awesome idea! I just made this.

Thank's for sharing your experience 🤠

**Comment by FabioOJacob** [comment]
@gustavosett in Windows the pinned clipboards are retained even when we log out. Here an exemple:

<img width="479" height="514" alt="Image" src="https://github.com/user-attachments/assets/d277760e-0a44-44ab-960d-841bf201f3a9" />

**Comment by jmwielandt** [comment]
@gustavosett you closed the issue about a bug with a pr of a new feature

i've just installed this on zorin os (debian based) and i have the same issue.
- version: 0.5.0

behaviour:
- super + v: writes a v
- ctrl + alt + v: opens the window, but it is not focused so I can't just use the arrow keys or press enter to paste; i need to use cursor and click on the window to focus the window.
